# Site settings
url: "https://eliabruni.github.io"
baseurl: ""
title: Elia Bruni
description: "Professor of Natural Language Processing at the University of Osnabrueck"

# Navigation
navbar-links:
  Publications: "publications"
  Teaching: "teaching"

# Author
author:
  name: Elia Bruni
  role: "Professor of Natural Language Processing"
  affiliation: "University of Osnabrueck"
  email: "elia.bruni@gmail.com"
  scholar: "https://scholar.google.com/citations?user=Oyb3NYgAAAAJ"
  github: "eliabruni"

# Build settings
timezone: "Europe/Amsterdam"
markdown: kramdown
permalink: /:year-:month-:day-:title/

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"

exclude:
  - CHANGELOG.md
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

plugins:
  - jekyll-sitemap
